### ISSUE TITLE
PokeApiNet.Models.Effects is missing property short_effect

### ISSUE THREAD

**Issue by mtrdp642** [mtrdp642/PokeApiNet#11]
In Common.cs, the class `Effects` is missing a field `short_effect`. The Effects class is used in `item`, `move`, and `ability` resources; all of these resources have this field in the `effect_entries` object. See [sample item](https://pokeapi.co/api/v2/item/1), [sample move](https://pokeapi.co/api/v2/move/1), and [sample ability](https://pokeapi.co/api/v2/ability/1). Backing code for [item](https://github.com/PokeAPI/pokeapi/blob/a5205b512640bd33684acbbb3f23a8d98aee0cbc/pokemon_v2/serializers.py#L1308), [move](https://github.com/PokeAPI/pokeapi/blob/a5205b512640bd33684acbbb3f23a8d98aee0cbc/pokemon_v2/serializers.py#L1986), and [ability](https://github.com/PokeAPI/pokeapi/blob/a5205b512640bd33684acbbb3f23a8d98aee0cbc/pokemon_v2/serializers.py#L1036).

This field is a string value that is a shorter version of the string in the `effect` property.

**Comment by jotatoledo** [comment]
Thats why there is also a `PokeApiNet.Models.VerboseEffect` class

**Comment by mtrdp642** [comment]
Fixed in #12
