### ISSUE TITLE
Pokemon Species missing IsLegendary and IsMythical

### ISSUE THREAD

**Issue by konvay** [mtrdp642/PokeApiNet#25]
The PokemonSpecies object is missing these two fields. The additional fields can be seen on the PokeApi `GET /pokemon-species/{name or id}/` route. 

https://pokeapi.co/api/v2/pokemon-species/ditto

**Comment by konvay** [comment]
I have the fields added in a local branch, but I push my branch to this repo. It's pretty small:

`        /// <summary>
        /// Whether or not this is a legendary Pokémon.
        /// </summary>
        [JsonProperty("is_legendary")]
        public bool IsLegendary { get; set; }

        /// <summary>
        /// Whether or not this is a mythical Pokémon.
        /// </summary>
        [JsonProperty("is_mythical")]
        public bool IsMythical { get; set; }`

**Comment by mtrdp642** [comment]
Thanks for finding this.

Feel free to fork this repo and push a PR so I can review and add this in, or I can make a release with this change in the next day or so.

For my own reference: [here's the code that added those fields](https://github.com/PokeAPI/pokeapi/blob/ad732576490d92f50b48d6bc57058c5f1265a5ee/pokemon_v2/models.py#L1638).

**Comment by konvay** [comment]
Awesome, here's the PR

https://github.com/mtrdp642/PokeApiNet/pull/26

**Comment by konvay** [comment]
Merged 👍
