### ISSUE TITLE
How a selected Pokemon's typing?

### ISSUE THREAD

**Issue by IssaJay01** [mtrdp642/PokeApiNet#28]
Ok so for my project I want the user to be able to pick a pokemon and have the typing for the pokemon displayed but I am having issues.

![image](https://user-images.githubusercontent.com/86020845/164045818-5ff17288-f794-4da2-bb98-1b39ba14dfb1.png)

So in the image this is how I am attempting to get the typing for Clefairy. I know it is wrong but when I tried to write in the same way that Clefairy's species is found I am getting errors.

![image](https://user-images.githubusercontent.com/86020845/164046285-c0b60c4b-ae01-4530-9773-7cda5e1a6a83.png)

I've been at this for hours and I am just trying to learn for personal practice so if anyone can help and explain how to get the typings for a Pokemon I would greatly appreciate it!

**Comment by mtrdp642** [comment]
Knowing exactly what type you need to use for `GetResourceAsync<T>` is a little tricky and does require you to both closely examine the return types and refer to [PokeAPI's documentation](https://pokeapi.co/docs/v2#pokemon). The model classes [very](https://pokeapi.co/docs/v2#berries) [closely](https://github.com/mtrdp642/PokeApiNet/blob/master/PokeApiNet/Models/Berries.cs#L17) match [the](https://pokeapi.co/docs/v2#evolution-chains) [naming](https://github.com/mtrdp642/PokeApiNet/blob/master/PokeApiNet/Models/Evolution.cs#L19) patterns of the [associated](https://pokeapi.co/docs/v2#pokemon) [server](https://github.com/mtrdp642/PokeApiNet/blob/master/PokeApiNet/Models/Pokemon.cs#L490) endpoints.

You'll want to use this for getting a Pokemon's types:
```cs
var id = "clefairy";
var pokemon = await pokeClient.GetResourceAsync<Pokemon>(id);

// pokemon.Types and pokemon.PastTypes for historical typing
pokemon.Types[0].Type.Name == "fairy";
```

**Comment by IssaJay01** [comment]
Thank you so much! I got it to work now! Learning different return types is quite tricky.
